modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
issueTrackerURL="https://github.com/gabbiechang/recipeMod" #optional

[[mods]] #mandatory
modId="kumquatrecipes" #mandatory
version="0.1" #mandatory
displayName="Recipes Mod" #mandatory
displayURL="https://github.com/gabbiechang/recipeMod" #optional
credits="Many thanks to Harry Talks for his various tutorials!" #optional
authors="@gabbiechang on github" #optional
description='''
This is a Minecraft mod that adds kumquat plants to the game, because they're delicious. 
Future updates will introduce new recipes as well. 
'''
[[dependencies.kumquatrecipes]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[25,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.kumquatrecipes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"